spring:
  datasource:
    username: ${Id}
    password: ${Password}
    url: jdbc:mysql://localhost:3306/umc6th?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create